// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simple.proto

package simple

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SimpleData struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleData) Reset()         { *m = SimpleData{} }
func (m *SimpleData) String() string { return proto.CompactTextString(m) }
func (*SimpleData) ProtoMessage()    {}
func (*SimpleData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ffd045dd4d042c1, []int{0}
}

func (m *SimpleData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleData.Unmarshal(m, b)
}
func (m *SimpleData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleData.Marshal(b, m, deterministic)
}
func (m *SimpleData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleData.Merge(m, src)
}
func (m *SimpleData) XXX_Size() int {
	return xxx_messageInfo_SimpleData.Size(m)
}
func (m *SimpleData) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleData.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleData proto.InternalMessageInfo

func (m *SimpleData) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SimpleData)(nil), "simple.SimpleData")
}

func init() { proto.RegisterFile("simple.proto", fileDescriptor_5ffd045dd4d042c1) }

var fileDescriptor_5ffd045dd4d042c1 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xce, 0xcc, 0x2d,
	0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xe4, 0xb8, 0xb8,
	0x82, 0xc1, 0x2c, 0x97, 0xc4, 0x92, 0x44, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0xd3, 0xc8, 0x8b, 0x8b, 0x17, 0x22, 0x1f, 0x9c, 0x5a, 0x54,
	0x96, 0x99, 0x9c, 0x2a, 0x64, 0xc9, 0xc5, 0x09, 0x11, 0x08, 0x0a, 0x70, 0x16, 0x12, 0xd2, 0x83,
	0x1a, 0x8a, 0x30, 0x43, 0x0a, 0x8b, 0x98, 0x12, 0x83, 0x06, 0xa3, 0x01, 0x63, 0x12, 0x1b, 0xd8,
	0x6a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x29, 0x3a, 0xd0, 0x8a, 0x00, 0x00, 0x00,
}
